# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "log_statement=all"]

  dbtools:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: example
    ports:
      - "5050:80"


  api:
    build: ./api
    ports:
      - "8080:8080"